version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
  
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - python test_db.py
  
  build:
    commands:
      - echo "Starting build phase..."
      - python migrations.py
  
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
  base-directory: '.'

cache:
  paths:
    - '/root/.cache/pip/**/*'